### ISSUE TITLE
it's very strange to get ID in path and in TenantRecord

### ISSUE THREAD

**Issue by arufanov** [a5lab/tabr#137]
it's very strange to get ID in path and in TenantRecord 
Which one to use?
For me it's better to post whole object with ID. 
Or Post id in path and data for object separatly

_Originally posted by @yurichervoniy in https://github.com/a5lab/tabr/pull/124#discussion_r1059653137_

**Comment by arufanov** [comment]
@yurichervoniy 
* lets discuss.

**Comment by yurichervoniy** [comment]
Ok, And?

**Comment by arufanov** [comment]
Included into #166
