### ISSUE TITLE
Make radar enable validation 

### ISSUE THREAD

**Issue by arufanov** [a5lab/tabr#142]
Useful links:
* https://www.baeldung.com/spring-mvc-custom-validator
* https://reflectoring.io/bean-validation-with-spring-boot/
* https://codingexplained.com/coding/java/hibernate/unique-field-validation-using-hibernate-spring 

@yurichervoniy 
* FYI

**Comment by arufanov** [comment]
@yurichervoniy lets discuss this issue.
* What should the home page have? Default radar or something else?
* If default radar then: what is default? Should we have is_default fields at database or something else? For example priority and show the radar with max priority? 
* Are you able to find validator to validate is_default field accross all records at www?

**Comment by yurichervoniy** [comment]
Are you able to find validator to validate is_default field accross all records at www? 
We can write our custom validator - fire SQL and check.
