### ISSUE TITLE
Make wiki page how to start table locally at dev environment

### ISSUE THREAD

**Issue by arufanov** [a5lab/tabr#214]
Make wiki page how to start table locally at dev environment

**Comment by A9afon** [comment]
The table is launched locally in the development environment through applications located in the tabr.a5lab.com repository. 

1. To do this, we clone the repository using the $ git clone tabr.a5lab.com command.

2. build this project with Java and Maven. 

- download java and maven. 

> define environment variables for Maven: in the path variable, specify the Maven path c:\...\apache-maven-3.8.7\ bin and also create a new M2_HOME variable - c:\...\apache-maven-3.8. 7

> create JAVA_HOME variable with path to jdk C:\Program Files\Java\jdk-19

3. To create a project, you need to install the uglify uglifycss packages

- for this you need to install the npm utilities
- download Node.js and install, then install the packages:

>  npm install -g uglifycss

> npm install uglify-js -gt

4. Build it via the command line in the root of the project: mvn clean package -Pdev -Dmaven.test.skip
then run the program mvn spring-boot:run -Pdev
5. Open a browser and enter 127.0.0.1:8080 and the application will open locally.
As a result, this application opens remotely
