### ISSUE TITLE
We have -dev, -prod profiles inside jar

### ISSUE THREAD

**Issue by arufanov** [a5lab/tabr#80]
@yurichervoniy 
tasks:
* [ ] remove statics/index.html file. It is used only for debug
* [ ] exclude all not minified resource: css as well as jscript
* [ ] exclude all -dev, -prod, -test profile. 

We have -dev, -prod profiles inside jar. Could you give me idea (link to docs): how to remove dev, prod , test profiles from jar. Thanks!

**Comment by arufanov** [comment]
@yurichervoniy 
* ?

**Comment by arufanov** [comment]
@yurichervoniy 
* could you provide some links?>

**Comment by yurichervoniy** [comment]
<build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

We can filter resources + using maven profiles we can add different filters

**Comment by yurichervoniy** [comment]
https://maven.apache.org/plugins/maven-resources-plugin/

**Comment by arufanov** [comment]
https://stackoverflow.com/questions/33379181/maven-resource-filtering-with-profile-properties
